"""Corrected unique user constraint

Revision ID: 0f832bad0dd5
Revises: 8b36aed2bc0b
Create Date: 2021-02-02 14:38:07.688745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f832bad0dd5'
down_revision = '8b36aed2bc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    # ### end Alembic commands ###
