"""second revision

Revision ID: 20ffc7ac29d4
Revises: b08bd3b600cd
Create Date: 2021-01-24 20:58:49.218392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ffc7ac29d4'
down_revision = 'b08bd3b600cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pages', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'pages', type_='unique')
    # ### end Alembic commands ###
