"""date_modified_to_users

Revision ID: 2ad4b201e338
Revises: fe37bd3c13d3
Create Date: 2021-01-24 21:03:16.592119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad4b201e338'
down_revision = 'fe37bd3c13d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
