"""set field settings

Revision ID: 65b85f9c6581
Revises: d4c14a060b11
Create Date: 2021-01-29 07:43:50.727487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b85f9c6581'
down_revision = 'd4c14a060b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
