"""Added page metadata table

Revision ID: 73be66301ee8
Revises: cdc93dcb9768
Create Date: 2021-02-10 11:03:45.124117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73be66301ee8'
down_revision = 'cdc93dcb9768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'page_metadata', ['page_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'page_metadata', type_='unique')
    # ### end Alembic commands ###
