"""Created a jobs table for APScheduler.

Revision ID: 8b36aed2bc0b
Revises: 936fb176be32
Create Date: 2021-02-02 11:33:44.184094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b36aed2bc0b'
down_revision = '936fb176be32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
