"""changed UUID field settings

Revision ID: 8f9f223976a8
Revises: d80d2b39b2c5
Create Date: 2021-01-27 12:16:16.385722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9f223976a8'
down_revision = 'd80d2b39b2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
