"""added user_id foreign key

Revision ID: 936fb176be32
Revises: 6759d11e0bdd
Create Date: 2021-01-29 08:23:42.703148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '936fb176be32'
down_revision = '6759d11e0bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('user_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'pages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.drop_column('pages', 'user_id')
    # ### end Alembic commands ###
