"""empty message

Revision ID: af36debd67d6
Revises: 584eeaa1d252
Create Date: 2021-01-24 21:56:53.213971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af36debd67d6'
down_revision = '584eeaa1d252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
