"""Moved page_url -> url

Revision ID: cdc93dcb9768
Revises: 0f832bad0dd5
Create Date: 2021-02-10 10:53:31.779015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc93dcb9768'
down_revision = '0f832bad0dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('pages', sa.Column('url', sa.String(), nullable=False))
    # op.drop_column('pages', 'page_url')
    op.alter_column('pages', 'page_url', new_column_name='url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('pages', sa.Column('page_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.drop_column('pages', 'url')
    op.alter_column('pages', 'url', new_column_name='page_url')
    # ### end Alembic commands ###
