"""empty message

Revision ID: fa5f60c1bfaa
Revises: 2ad4b201e338
Create Date: 2021-01-24 21:04:52.292997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5f60c1bfaa'
down_revision = '2ad4b201e338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_modified')
    # ### end Alembic commands ###
