"""date_modified_to_users

Revision ID: fe37bd3c13d3
Revises: 20ffc7ac29d4
Create Date: 2021-01-24 21:01:22.300915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe37bd3c13d3'
down_revision = '20ffc7ac29d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
