// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbqueries

import (
	"database/sql"
	"time"
)

type Page struct {
	ID                  string
	UserID              string
	Url                 string
	Title               sql.NullString
	Description         sql.NullString
	ImageUrl            sql.NullString
	ReadabilityStatus   sql.NullString
	ReadabilityTaskData sql.NullString
	IsReadable          sql.NullBool
	Created             time.Time
	Updated             time.Time
}

type SchemaMigration struct {
	Version string
}

type User struct {
	ID             string
	Username       string
	Email          string
	Password       interface{}
	Avatar         sql.NullString
	Subscribed     bool
	ShortcutToken  string
	HasReadability bool
	Created        time.Time
	Updated        time.Time
}
