// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbqueries

import (
	"database/sql"
	"time"
)

type Page struct {
	ID                  interface{}
	UserID              interface{}
	Url                 interface{}
	Title               interface{}
	Description         interface{}
	ImageUrl            interface{}
	ReadabilityStatus   interface{}
	ReadabilityTaskData interface{}
	IsReadable          sql.NullBool
	Created             time.Time
	Updated             time.Time
}

type SchemaMigrations struct {
	Version string
}

type User struct {
	ID             interface{}
	Username       interface{}
	Email          interface{}
	Password       interface{}
	Name           interface{}
	Avatar         interface{}
	Subscribed     sql.NullBool
	ShortcutToken  interface{}
	HasReadability sql.NullBool
	Created        time.Time
	Updated        time.Time
}
