// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.501
package render

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/mr55p-dev/pagemail/internal/db"
	"time"
)

func MailDigest(date *time.Time, name string, pages []db.Page) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html><head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `pagemail digest from `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(date.Format("02-01-2006"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/render/mail.templ`, Line: 13, Col: 58}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</title><style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := `
      /* -------------------------------------
              GLOBAL RESETS
          ------------------------------------- */

      /*All the styling goes here*/

      img {
      	border: none;
      	-ms-interpolation-mode: bicubic;
      	max-width: 100%;
      }

      body {
      	background-color: #f6f6f6;
      	font-family: sans-serif;
      	-webkit-font-smoothing: antialiased;
      	font-size: 14px;
      	line-height: 1.4;
      	margin: 0;
      	padding: 0;
      	-ms-text-size-adjust: 100%;
      	-webkit-text-size-adjust: 100%;
      }

      table {
      	border-collapse: separate;
      	mso-table-lspace: 0pt;
      	mso-table-rspace: 0pt;
      	width: 100%;
      }

      table td {
      	font-family: sans-serif;
      	font-size: 14px;
      	vertical-align: top;
      }

      /* -------------------------------------
              BODY & CONTAINER
          ------------------------------------- */

      .body {
      	background-color: #f6f6f6;
      	width: 100%;
      }

      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
      .container {
      	display: block;
      	margin: 0 auto !important;
      	/* makes it centered */
      	max-width: 580px;
      	padding: 10px;
      	width: 580px;
      	overflow-x: hidden;
      }

      /* This should also be a block element, so that it will fill 100% of the .container */
      .content {
      	box-sizing: border-box;
      	display: block;
      	margin: 0 auto;
      	max-width: 580px;
      	padding: 10px;
      }

      /* -------------------------------------
              HEADER, FOOTER, MAIN
          ------------------------------------- */
      .main {
      	background: #ffffff;
      	border-radius: 3px;
      	width: 100%;
      }

      .wrapper {
      	box-sizing: border-box;
      	padding: 20px;
      }

      .content-block {
      	padding-bottom: 10px;
      	padding-top: 10px;
      }

      .footer {
      	clear: both;
      	margin-top: 10px;
      	text-align: center;
      	width: 100%;
      }

      .footer td,
      .footer p,
      .footer span,
      .footer a {
      	color: #999999;
      	font-size: 12px;
      	text-align: center;
      }

      /* -------------------------------------
              TYPOGRAPHY
          ------------------------------------- */
      h1,
      h2,
      h3,
      h4 {
      	color: #000000;
      	font-family: sans-serif;
      	font-weight: 400;
      	line-height: 1.4;
      	margin: 0;
      	margin-bottom: 30px;
      }

      h1 {
      	font-size: 35px;
      	font-weight: 300;
      	text-align: center;
      	text-transform: capitalize;
      }

      p,
      ul,
      ol {
      	font-family: sans-serif;
      	font-size: 14px;
      	font-weight: normal;
      	margin: 0;
      	margin-bottom: 15px;
      }

      p li,
      ul li,
      ol li {
      	list-style-position: inside;
      	margin-left: 5px;
      }

      a {
      	color: #3498db;
      	text-decoration: underline;
      }

      /* -------------------------------------
              BUTTONS
          ------------------------------------- */
      .btn {
      	box-sizing: border-box;
      	width: 100%;
      }

      .btn>tbody>tr>td {
      	padding-bottom: 15px;
      }

      .btn table {
      	width: auto;
      }

      .btn table td {
      	background-color: #ffffff;
      	border-radius: 5px;
      	text-align: center;
      }

      .btn a {
      	background-color: #ffffff;
      	border: solid 1px #3498db;
      	border-radius: 5px;
      	box-sizing: border-box;
      	color: #3498db;
      	cursor: pointer;
      	display: inline-block;
      	font-size: 14px;
      	font-weight: bold;
      	margin: 0;
      	padding: 12px 25px;
      	text-decoration: none;
      	text-transform: capitalize;
      }

      .btn-primary table td {
      	background-color: #3498db;
      }

      .btn-primary a {
      	background-color: #3498db;
      	border-color: #3498db;
      	color: #ffffff;
      }

      /* -------------------------------------
              OTHER STYLES THAT MIGHT BE USEFUL
          ------------------------------------- */
      .last {
      	margin-bottom: 0;
      }

      .first {
      	margin-top: 0;
      }

      .align-center {
      	text-align: center;
      }

      .align-right {
      	text-align: right;
      }

      .align-left {
      	text-align: left;
      }

      .clear {
      	clear: both;
      }

      .mt0 {
      	margin-top: 0;
      }

      .mb0 {
      	margin-bottom: 0;
      }

      .preheader {
      	color: transparent;
      	display: none;
      	height: 0;
      	max-height: 0;
      	max-width: 0;
      	opacity: 0;
      	overflow: hidden;
      	mso-hide: all;
      	visibility: hidden;
      	width: 0;
      }

      .powered-by a {
      	text-decoration: none;
      }

      hr {
      	border: 0;
      	border-bottom: 1px solid #f6f6f6;
      	margin: 20px 0;
      }

      /* -------------------------------------
              RESPONSIVE AND MOBILE FRIENDLY STYLES
          ------------------------------------- */
      @media only screen and (max-width: 620px) {
      	table.body h1 {
      		font-size: 28px !important;
      		margin-bottom: 10px !important;
      	}

      	table.body p,
      	table.body ul,
      	table.body ol,
      	table.body td,
      	table.body span,
      	table.body a {
      		font-size: 16px !important;
      	}

      	table.body .wrapper,
      	table.body .article {
      		padding: 10px !important;
      	}

      	table.body .content {
      		padding: 0 !important;
      	}

      	table.body .container {
      		padding: 0 !important;
      		width: 100% !important;
      	}

      	table.body .main {
      		border-left-width: 0 !important;
      		border-radius: 0 !important;
      		border-right-width: 0 !important;
      	}

      	table.body .btn table {
      		width: 100% !important;
      	}

      	table.body .btn a {
      		width: 100% !important;
      	}

      	table.body .img-responsive {
      		height: auto !important;
      		max-width: 100% !important;
      		width: auto !important;
      	}
      }

      /* -------------------------------------
              PRESERVE THESE STYLES IN THE HEAD
          ------------------------------------- */
      @media all {
      	.ExternalClass {
      		width: 100%;
      	}

      	.ExternalClass,
      	.ExternalClass p,
      	.ExternalClass span,
      	.ExternalClass font,
      	.ExternalClass td,
      	.ExternalClass div {
      		line-height: 100%;
      	}

      	.apple-link a {
      		color: inherit !important;
      		font-family: inherit !important;
      		font-size: inherit !important;
      		font-weight: inherit !important;
      		line-height: inherit !important;
      		text-decoration: none !important;
      	}

      	#MessageViewBody a {
      		color: inherit;
      		text-decoration: none;
      		font-size: inherit;
      		font-family: inherit;
      		font-weight: inherit;
      		line-height: inherit;
      	}

      	.btn-primary table td:hover {
      		background-color: #34495e !important;
      	}

      	.btn-primary a:hover {
      		background-color: #34495e !important;
      		border-color: #34495e !important;
      	}
      }

      /*-------------------------------------
        MY CODE
      --------------------------------------/*
    `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</style></head><body><span class=\"preheader\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var5 := `pagemail saved pages from `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(date.Format("02-01-2006"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/render/mail.templ`, Line: 370, Col: 80}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span><table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\"><tr><td>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var7 := `&nbsp;`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</td><td class=\"container\"><div class=\"content\"><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var8 := ` START CENTERED WHITE CONTAINER `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><table role=\"presentation\" class=\"main\"><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var9 := ` START MAIN CONTENT AREA `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var9)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><tr><td class=\"wrapper\"><table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr><td><p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var10 := `Good morning `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var10)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var11 string
		templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/render/mail.templ`, Line: 395, Col: 35}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var12 := `Here are all the pages you've saved since `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var12)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var13 string
		templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(date.Format("02-01-2006"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/render/mail.templ`, Line: 397, Col: 83}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><ul class=\"main-list\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, page := range pages {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<li class=\"main-list-item\"><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var14 templ.SafeURL = templ.URL(page.Url)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var14)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if page.Title != nil {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<b>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var15 string
				templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs(*page.Title)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/render/mail.templ`, Line: 404, Col: 34}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</b> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if page.Description != nil {
					templ_7745c5c3_Var16 := `- `
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var16)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var17 string
					templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(*page.Description)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/render/mail.templ`, Line: 406, Col: 40}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			} else {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<b>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var18 string
				templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.JoinStringErrs(page.Url)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/render/mail.templ`, Line: 409, Col: 31}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var18))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</b>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</a> <i><span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var19 string
			templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.JoinStringErrs(page.Created.Format("02/01 15:04"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/render/mail.templ`, Line: 412, Col: 61}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var19))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span></i></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</ul></td></tr></table></td></tr><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var20 := ` END MAIN CONTENT AREA `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var20)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--></table><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var21 := ` END CENTERED WHITE CONTAINER `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var21)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var22 := ` START FOOTER `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var22)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><div class=\"footer\"><table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr><td class=\"content-block\"><span class=\"apple-link\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var23 := `Thank's for subscribing to pagemail!`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var23)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span><br>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var24 := `Don't like these emails?`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var24)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" <a href=\"https://pagemail.io/account\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var25 := `Unsubscribe`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var25)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</a>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var26 := `.`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var26)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</td></tr><tr><td class=\"content-block powered-by\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var27 := `Powered by `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var27)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"http://htmlemail.io\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var28 := `HTMLemail`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var28)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</a>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var29 := `.`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var29)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</td></tr></table></div><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var30 := ` END FOOTER `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var30)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--></div></td><td>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var31 := `&nbsp;`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var31)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</td></tr></table></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
