root = "."

[build]
  bin = "./pagemail"
  pre_cmd = ["make clean"]
  cmd = "make pagemail"
  exclude_dir = []
  exclude_regex = ["render.*css", "^tailwind"]
  include_dir = ["assets/css", "cmd", "db/queries", "internal"]
  include_ext = ["go", "css"]
  send_interrupt = true
  delay = 1000


[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
