---
version: v3
name: pagemail
services:
  pagemail:
    extends:
      file: docker-compose.base.yml
      service: pagemail
    image: 168938868801.dkr.ecr.eu-west-2.amazonaws.com/pagemail:prd
    container_name: pagemail-prd
    environment:
      PM_ENVIRONMENT: prd
      PM_LOG_LEVEL: INFO
      PM_GOOGLE_CLIENT_ID: "556909502728-4s4ibjtkcpjrdq634a7se19qd86oilrk.apps.googleusercontent.com"
    volumes:
      - type: bind
        source: /home/ubuntu/pagemail/prd/
        target: /data/
    secrets:
      - cookie-key
    logging:
      options:
        awslogs-group: /splat/pagemail
    labels:
      - "traefik.http.routers.pagemail-prd.rule=Host(`pagemail.io`)"
      - "traefik.http.routers.pagemail-prd.entrypoints=websecure"
      - "traefik.http.routers.pagemail-prd.tls.certresolver=letsencrypt"

networks:
  traefik:
    name: traefik_proxy
    external: true

secrets:
  cookie-key:
    file: /home/ubuntu/pagemail/prd/cookie-key.txt
