---
version: v3
name: pagemail
services:
  pagemail:
    extends:
      file: docker-compose.base.yml
      service: pagemail
    image: 168938868801.dkr.ecr.eu-west-2.amazonaws.com/pagemail:prd
    container_name: pagemail-prd
    environment:
      PM_ENVIRONMENT: prd
      PM_LOG_LEVEL: INFO
    volumes:
      - ./pagemail/prd/db:/app/db
    logging:
      options:
        awslogs-group: /splat/pagemail
    labels:
      - "traefik.http.routers.pagemail-dev.rule=Host(`pagemail.io`)"

networks:
  traefik:
    name: traefik_proxy
    external: true
