---
version: v3
name: pagemail-dev
services:
  pagemail:
    extends:
      file: docker-compose.base.yml
      service: pagemail
    image: 168938868801.dkr.ecr.eu-west-2.amazonaws.com/pagemail:latest
    container_name: pagemail-dev
    environment:
      PM_APP_ENVIRONMENT: dev
      PM_APP_LOG_LEVEL: DEBUG
      PM_APP_GOOGLE_CLIENT_ID: "556909502728-4s4ibjtkcpjrdq634a7se19qd86oilrk.apps.googleusercontent.com"
      PM_EXTERN_HOST: dev.pagemail.io
      PM_EXTERN_PROTO: https
    volumes:
      - type: bind
        source: /home/ubuntu/pagemail/dev/
        target: /data/
    secrets:
      - cookie-key
    logging:
      options:
        awslogs-group: /splat/pagemail-dev
    labels:
      - "traefik.http.routers.pagemail-dev.rule=Host(`dev.pagemail.io`)"
      - "traefik.http.routers.pagemail-dev.entrypoints=websecure"
      - "traefik.http.routers.pagemail-dev.tls.certresolver=letsencrypt"

  readability:
    image: 168938868801.dkr.ecr.eu-west-2.amazonaws.com/pagemail-readability:latest
    container_name: pagemail-readability-dev
    environment:
      RDR_HOST: 0.0.0.0
      RDR_PORT: 80
      RDR_BUCKET_NAME: pagemail-readability
      RDR_PREFIX_NAME: dev/
    logging:
      driver: awslogs
      options:
        awslogs-group: /splat/pagemail-readability-dev
        awslogs-region: eu-west-2

networks:
  traefik:
    name: traefik_proxy
    external: true

secrets:
  cookie-key:
    file: /home/ubuntu/pagemail/dev/cookie-key.txt
