---
version: v3
name: pagemail-dev
services:
  pagemail:
    extends:
      file: docker-compose.base.yml
      service: pagemail
    image: 168938868801.dkr.ecr.eu-west-2.amazonaws.com/pagemail:latest
    container_name: pagemail-dev
    environment:
      PM_ENVIRONMENT: dev
      PM_LOG_LEVEL: DEBUG
    volumes:
      - type: bind
        source: /home/ubuntu/pagemail/dev/
        target: /data/
    secrets:
      - cookie-key
    logging:
      options:
        awslogs-group: /splat/pagemail-dev
    labels:
      - "traefik.http.routers.pagemail-dev.rule=Host(`dev.pagemail.io`)"
      - "traefik.http.routers.pagemail-dev.entrypoints=websecure"
      - "traefik.http.routers.pagemail-dev.tls.certresolver=letsencrypt"

networks:
  traefik:
    name: traefik_proxy
    external: true

secrets:
  cookie-key:
    file: /home/ubuntu/pagemail/dev/cookie-key.txt
