---
version: v3
name: pagemail
services:
  pagemail:
    extends:
      file: docker-compose.base.yml
      service: pagemail
    image: 168938868801.dkr.ecr.eu-west-2.amazonaws.com/pagemail:prd
    container_name: pagemail-prd
    environment:
      PM_APP_ENVIRONMENT: prd
      PM_APP_LOG_LEVEL: INFO
      PM_APP_GOOGLE_CLIENT_ID: "556909502728-88okrlq3elmg013h5p20hhs53ls46d3s.apps.googleusercontent.com"
      PM_EXTERN_HOST: pagemail.io
      PM_EXTERN_PROTO: https
    volumes:
      - type: bind
        source: /home/ubuntu/pagemail/prd/
        target: /data/
    secrets:
      - cookie-key
    logging:
      options:
        awslogs-group: /splat/pagemail
    labels:
      - "traefik.http.routers.pagemail-prd.rule=Host(`pagemail.io`)"
      - "traefik.http.routers.pagemail-prd.entrypoints=websecure"
      - "traefik.http.routers.pagemail-prd.tls.certresolver=letsencrypt"

  readability:
    extends:
      file: docker-compose.base.yml
      service: readability
    image: 168938868801.dkr.ecr.eu-west-2.amazonaws.com/pagemail-readability:prd
    environment:
      RDR_PREFIX_NAME: prd/
    logging:
      options:
        awslogs-group: /splat/pagemail-readability

networks:
  readability:
  traefik:
    name: traefik_proxy
    external: true

secrets:
  cookie-key:
    file: /home/ubuntu/pagemail/prd/cookie-key.txt
