---
version: v3
name: pagemail
services:
  pagemail:
    extends:
      file: docker-compose.base.yaml
      service: pagemail
    image: pagemail:latest
    container_name: pagemail-prd
    environment:
      PM_ENVIRONMENT: prd
      PM_LOG_LEVEL: INFO
    volumes:
      - ./pagemail/prd/db:/app/db
    logging:
      options:
        awslogs-group: /splat/pagemail
    labels:
      - "traefik.http.routers.pagemail-dev.rule=Host(`pagemail.io`)"
