---
version: v3
name: pagemail-dev
services:
  pagemail:
    extends:
      file: docker-compose.base.yaml
      service: pagemail
    image: pagemail:latest
    container_name: pagemail-dev
    environment:
      PM_ENVIRONMENT: dev
      PM_LOG_LEVEL: DEBUG
    volumes:
      - ./pagemail/dev/db:/app/db
    logging:
      options:
        awslogs-group: /splat/pagemail-dev
    labels:
      - "traefik.http.routers.pagemail-dev.rule=Host(`dev.pagemail.io`)"
