---
version: v3
services:
  pagemail:
    restart: always
    expose:
      - 80
    environment:
      PM_APP_HOST: 0.0.0.0:80
      PM_DB_PATH: /data/db/pagemail.sqlite3
      PM_APP_COOKIE_KEY_FILE: /run/secrets/cookie-key
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-2
    platform: linux/amd64
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
