---
version: v3
name: pagemail
services:
  pagemail:
    extends:
      file: docker-compose.base.yml
      service: pagemail
    depends_on:
      readability:
        condition: service_healthy
    image: 168938868801.dkr.ecr.eu-west-2.amazonaws.com/pagemail:prd
    container_name: pagemail-prd
    environment:
      PM_APP_ENVIRONMENT: prd
      PM_APP_LOG_LEVEL: INFO
      PM_APP_GOOGLE_CLIENT_ID: "556909502728-88okrlq3elmg013h5p20hhs53ls46d3s.apps.googleusercontent.com"
      PM_EXTERN_HOST: pagemail.io
      PM_EXTERN_PROTO: https
    networks:
      - readability
      - traefik
    volumes:
      - type: bind
        source: /home/ubuntu/pagemail/prd/
        target: /data/
    secrets:
      - cookie-key
    logging:
      options:
        awslogs-group: /splat/pagemail
    labels:
      - "traefik.http.routers.pagemail-prd.rule=Host(`pagemail.io`)"
      - "traefik.http.routers.pagemail-prd.entrypoints=websecure"
      - "traefik.http.routers.pagemail-prd.tls.certresolver=letsencrypt"

  readability:
    image: 168938868801.dkr.ecr.eu-west-2.amazonaws.com/pagemail-readability:prd
    container_name: pagemail-readability
    environment:
      RDR_HOST: 0.0.0.0
      RDR_PORT: 80
      RDR_BUCKET_NAME: pagemail-readability
      RDR_PREFIX_NAME: prd/
    expose:
      - 5000
    networks:
      - traefik
      - readability
    logging:
      driver: awslogs
      options:
        awslogs-group: /splat/pagemail-readability
        awslogs-region: eu-west-2
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5000/health"]
      interval: 10s
      timeout: 2s
      retries: 0
      start_period: 10s

networks:
  readability:
  traefik:
    name: traefik_proxy
    external: true

secrets:
  cookie-key:
    file: /home/ubuntu/pagemail/prd/cookie-key.txt
