---
version: v3
services:
  pagemail:
    restart: always
    expose:
      - 80
    environment:
      PM_APP_HOST: 0.0.0.0:80
      PM_DB_PATH: /data/db/pagemail.sqlite3
      PM_APP_COOKIE_KEY_FILE: /run/secrets/cookie-key
      PM_READABILITY_SCHEME: http
      PM_READABILITY_HOST: readability:80
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-2
    networks:
      - readability
      - traefik
    platform: linux/amd64
    labels:
      - "traefik.enable=true"

  readability:
    restart: always
    environment:
      RDR_PORT: 80
      RDR_BUCKET_NAME: pagemail-readability
    expose:
      - 80
    networks:
      - readability
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-2
    healthcheck:
      test: ["CMD", "curl", "http://localhost:80/health"]
      interval: 10s
      timeout: 2s
      retries: 0
      start_period: 10s
