---
version: v3
name: pagemail-dev
services:
  pagemail:
    extends:
      file: docker-compose.base.yml
      service: pagemail
    image: 168938868801.dkr.ecr.eu-west-2.amazonaws.com/pagemail:latest
    container_name: pagemail-dev
    environment:
      PM_ENVIRONMENT: dev
      PM_LOG_LEVEL: DEBUG
    volumes:
      - ./pagemail/dev/db:/app/db
    logging:
      options:
        awslogs-group: /splat/pagemail-dev
    labels:
      - "traefik.http.routers.pagemail-dev.rule=Host(`dev.pagemail.io`)"
      - "traefik.http.routers.pagemail-prd.entrypoints=websecure"
      - "traefik.http.routers.pagemail-prd.tls.certresolver=letsencrypt"

networks:
  traefik:
    name: traefik_proxy
    external: true
