---
version: v3
services:
  pagemail:
    restart: always
    expose:
      - 80
    environment:
      PM_APP_HOST: 0.0.0.0:80
      PM_DB_PATH: /data/db/pagemail.sqlite3
      PM_APP_COOKIE_KEY_FILE: /run/secrets/cookie-key
      PM_AWS_PROFILE: pagemail
      PM_AWS_CONFIG_FILE: /run/secrets/aws-config
      PM_AWS_CREDENTIALS_FILE: /run/secrets/aws-credentials
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-2
    networks:
      - traefik
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
