services:
  pagemail:
    # image: 168938868801.dkr.ecr.eu-west-2.amazonaws.com/pagemail:latest
    image: pagemail:latest
    container_name: pagemail
    environment:
      PM_ENVIRONMENT: prd
      PM_LOG_LEVEL: INFO
      PM_MODE: release
      PM_HOST: 0.0.0.0:8080
      PM_PATH: /app/db/pagemail.sqlite3
    ports:
      - 8080:3000
    volumes:
      - db:/app/db
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-2
        awslogs-group: /splat/pagemail
    labels:
      traefik.enable: true
      traefik.http.routers.pagemail.rule: Host("pagemail.io")
      traefik.http.routers.pagemail.entrypoints: web
      # traefik.http.routers.pagemail.tls.certresolver: letsencrypt
    platform: linux/amd64

volumes:
  db:
