// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Platform    string
	Credential  string
	ResetToken  pgtype.Text
	ResetExpiry pgtype.Timestamp
	Created     pgtype.Timestamp
	Updated     pgtype.Timestamp
}

type Page struct {
	ID          string
	UserID      uuid.UUID
	Url         string
	Title       pgtype.Text
	Description pgtype.Text
	ImageUrl    pgtype.Text
	Created     pgtype.Timestamp
	Updated     pgtype.Timestamp
}

type Schedule struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Timezone string
	Days     int32
	Hour     int32
	Minute   int32
	LastSent pgtype.Timestamp
}

type User struct {
	ID             uuid.UUID
	Email          string
	Username       string
	HasReadability bool
	Created        pgtype.Timestamp
	Updated        pgtype.Timestamp
}
