// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"database/sql"
	"time"
)

type Auth struct {
	ID                  int64
	UserID              string
	Platform            string
	PasswordHash        []byte
	PasswordResetToken  []byte
	PasswordResetExpiry sql.NullTime
	Credential          []byte
	Created             time.Time
	Updated             time.Time
}

type Page struct {
	ID               string
	UserID           string
	Url              string
	Title            sql.NullString
	Description      sql.NullString
	ImageUrl         sql.NullString
	PreviewState     string
	Created          time.Time
	Updated          time.Time
	Readable         bool
	ReadingJobStatus interface{}
	ReadingJobID     interface{}
}

type SchemaMigration struct {
	Version string
}

type User struct {
	ID             string
	Email          string
	Username       string
	Subscribed     bool
	HasReadability bool
	Created        time.Time
	Updated        time.Time
}
