// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.readings.sql

package queries

import (
	"context"
	"database/sql"
)

const getReadingsByUser = `-- name: GetReadingsByUser :many
SELECT id, user_id, article_id, job_id, state, reason, created, updated FROM readings
WHERE user_id = ?
`

func (q *Queries) GetReadingsByUser(ctx context.Context, userID string) ([]Reading, error) {
	rows, err := q.db.QueryContext(ctx, getReadingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ArticleID,
			&i.JobID,
			&i.State,
			&i.Reason,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newReading = `-- name: NewReading :one
INSERT INTO readings 
	(id, user_id, article_id, job_id, state) 
VALUES 
	(?, ?, ?, ?, ?)
RETURNING id, user_id, article_id, job_id, state, reason, created, updated
`

type NewReadingParams struct {
	ID        string
	UserID    string
	ArticleID string
	JobID     string
	State     string
}

func (q *Queries) NewReading(ctx context.Context, arg NewReadingParams) (Reading, error) {
	row := q.db.QueryRowContext(ctx, newReading,
		arg.ID,
		arg.UserID,
		arg.ArticleID,
		arg.JobID,
		arg.State,
	)
	var i Reading
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArticleID,
		&i.JobID,
		&i.State,
		&i.Reason,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateReading = `-- name: UpdateReading :exec
UPDATE readings
SET state = ?,
	reason = ?,
	updated = CURRENT_TIMESTAMP
`

type UpdateReadingParams struct {
	State  string
	Reason sql.NullString
}

func (q *Queries) UpdateReading(ctx context.Context, arg UpdateReadingParams) error {
	_, err := q.db.ExecContext(ctx, updateReading, arg.State, arg.Reason)
	return err
}
