basePath: /
host: localhost:8080
info:
  contact: {}
  description: The documentation for the web-app and API of pagemail
  title: Pagemail API documentation
  version: "1.0"
paths:
  /:
    get:
      produces:
      - text/html
      - text/json
      responses:
        "200":
          description: OK
      summary: Get the landing page
      tags:
      - page
swagger: "2.0"
