---
name: Deploy to production
on:
  push:
    tags:
      - "v*"
jobs:
  deploy:
    name: Deploy production
    uses: ./.github/workflows/deploy-env.yaml
    with:
      environment: Production
    secrets: inherit
  migrate:
    name: Run migrations
    uses: ./.github/workflows/run-migration.yaml
    with:
      environment: Production
    secrets: inherit
