---
name: Deploy to development
on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    name: Deploy development
    uses: ./.github/workflows/deploy-env.yaml
    with:
      environment: Development
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
