---
name: Deploy to dokku
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - v6

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ vars.DOKKU_HOST }}/pagemailv6
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          branch: master
          command: deploy
