---
name: Deploy to production
on:
  release:
    types:
      - released
jobs:
  deploy:
    name: Deploy production
    uses: ./.github/workflows/deploy-env.yaml
    with:
      environment: Production
    secrets: inherit
