---
name: Deploy code to stage

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.5"
          cache: true
          cache-dependency-path: server/go.sum

      - name: Install dependencies
        run: make install

      - name: Build binary
        run: make build

      - name: Store build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ github.workspace }}/tmp/main

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download backend
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build/

      - name: Clean environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: rm -rf /home/ec2-user/pagemail

      - name: Copy build artifact onto server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "build/main"
          target: /home/ec2-user/stg/pagemail/
          strip_components: 1

      - name: Copy server files onto server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "install.sh,nginx/*,services/*,test_pages/*"
          target: /home/ec2-user/pagemail

      - name: Run install script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.key }}
          port: ${{ secrets.port }}
          script: sudo bash /home/ec2-user/pagemail/install.sh /home/ec2-user/pagemail stg
