---
name: Deploy to development
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy development
    uses: ./.github/workflows/deploy-env.yaml
    with:
      environment: Development
    secrets: inherit
