---
name: Deploy code
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment to deploy into
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy into
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  server-login:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Disable host verification
        run: echo "StrictHostKeyChecking no" >> $HOME/.ssh/config

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Log into docker via server
        env:
          DOCKER_HOST: ${{ vars.DOCKER_HOST }}
        run: |
          docker login \
          --username ${{ steps.login-ecr.outputs.docker_username_168938868801_dkr_ecr_eu_west_2_amazonaws_com }} \
          --password ${{ steps.login-ecr.outputs.docker_password_168938868801_dkr_ecr_eu_west_2_amazonaws_com }} \
          ${{ steps.login-ecr.outputs.registry }}

  build-pagemail:
    needs:
      - server-login
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: pagemail
          IMAGE_TAG: ${{ vars.CONTAINER_LABEL }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  build-readability:
    needs:
      - server-login
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: pagemail-readability
          IMAGE_TAG: ${{ vars.CONTAINER_LABEL }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG readability/
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-pagemail
      - build-readability
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Disable host verification
        run: echo "StrictHostKeyChecking no" >> $HOME/.ssh/config

      - name: Deploy to server
        env:
          DOCKER_HOST: ${{ vars.DOCKER_HOST }}
          COMPOSE_FILE: docker-compose.${{ vars.ENV_NAME }}.yml
        run: |
          docker compose -f $COMPOSE_FILE down
          docker compose -f $COMPOSE_FILE rm -f
          docker compose -f $COMPOSE_FILE pull
          docker compose -f $COMPOSE_FILE up -d
