---
name: "deploy"

# yamllint disable-line rule:truthy
on: pull_request

jobs:
  review_app:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ vars.DOKKU_HOST }}/pagemail
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          command: "review-apps:create"
          review_app_name: review-${{ github.event.pull_request.number }}-pagemail
          branch: v6
