---
name: Run migrations
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment to migrate
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to migrate
        required: true
  push:
    branches:
      - main
    paths:
      - "db/migrations/*"

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Disable host verification
        run: echo "StrictHostKeyChecking no" >> $HOME/.ssh/config

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        id: build
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: pagemail-migrations
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f Dockerfile.migrations .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Log into docker via server
        env:
          DOCKER_HOST: ${{ vars.DOCKER_HOST }}
        run: |
          docker login \
          --username ${{ steps.login-ecr.outputs.docker_username_168938868801_dkr_ecr_eu_west_2_amazonaws_com }} \
          --password ${{ steps.login-ecr.outputs.docker_password_168938868801_dkr_ecr_eu_west_2_amazonaws_com }} \
          ${{ steps.login-ecr.outputs.registry }}

      - name: Deploy to server
        env:
          DOCKER_HOST: ${{ vars.DOCKER_HOST }}
        run: |
          docker run --rm \
          -v /home/ubuntu/pagemail/${{ vars.ENV_NAME }}/db:/db \
          -e DATABASE_URL=sqlite3:/db/pagemail.sqlite3 \
          -e DBMATE_MIGRATIONS_DIR=/migrations \
          -e DBMATE_NO_DUMP_SCHEMA=1 \
          ${{ steps.build.outputs.image }} migrate
