---
name: Run migrations
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment to migrate
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to migrate
        required: true
  push:
    branches:
      - main
    paths:
      - "db/migrations/*"

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Disable host verification
        run: echo "StrictHostKeyChecking no" >> $HOME/.ssh/config

      - name: docker-context-create
        uses: ArwynFr/actions-docker-context@v2
        with:
          docker_host: ${{ vars.DOCKER_HOST }}
          context_name: remote
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          use_context: true

      - name: Build
        id: build
        run: |
          docker build -t pagemail-migrations:latest -f Dockerfile.migrations .

      - name: Deploy to server
        run: |
          docker run --rm \
          -v /home/ubuntu/pagemail/${{ vars.ENV_NAME }}/db:/db \
          -e DATABASE_URL=sqlite3:/db/pagemail.sqlite3 \
          -e DBMATE_MIGRATIONS_DIR=/migrations \
          -e DBMATE_NO_DUMP_SCHEMA=1 \
          pagemail-migrations:latest
