---
name: Cleanup images
on:
  workflow_dispatch:
  workflow_call:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Disable host verification
        run: echo "StrictHostKeyChecking no" >> $HOME/.ssh/config

      - name: docker-context-create
        uses: ArwynFr/actions-docker-context@v2
        with:
          docker_host: ${{ vars.DOCKER_HOST }}
          context_name: remote
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          use_context: true

      - name: Build
        id: build
        run: |
          docker image rm $(docker image ls -f "dangling=true" -q)
