---
name: On merge main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      bumped: ${{ steps.bump.outputs.part }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: none

  deploy-prd:
    name: Deploy production
    needs: tag
    if: needs.tag.outputs.bumped != 'none'
    uses: ./.github/workflows/deploy-prd.yaml
    secrets: inherit
